### ISSUE TITLE
CC2650 Binary code size more than 128kb

### ISSUE THREAD

**Issue by Adu143** [contiki-ng/contiki-ng#537] opened 2018-05-22 15:55 UTC
I am unable to load the bin file generated for cc2650 examples since it is more than 128kb. Is there any way i can reduce it or have i missed something during my compilation?

**Comment by g-oikonomou** [comment] 2018-05-22 15:58
If you have made no changes to the code, then you must have missed something during either the build stage or while programming the device

**Comment by Adu143** [comment] 2018-05-22 16:03
I have not done any code changes. I compiled the toolchain (Linux) followed by a 'make' for the board cc2650. It generated a bin file of 131kb for Very Sleepy Demo.

**Comment by niziak** [comment] 2018-05-22 19:27
New newlibc grows a bit. Try to add to Makefile:
```
LDFLAGS += -specs=nosys.specs
LDFLAGS += -specs=nano.specs
```
but even with this you cannot get sizes from older toolchain.

**Comment by g-oikonomou** [comment] 2018-05-22 21:14
The file size of the .bin is irrelevant. If newlib has grown we perhaps need to have a look into this.

> but even with this you cannot get sizes from older toolchain.

I cannot say I immediately understand what you are trying to say here, @niziak

**Comment by niziak** [comment] 2018-05-23 05:46
Ok, I'm to fast. Maybe my comment is not relevant to this issue.

In my project I noticed serious code grow up (by 30kB) when the same source was compiled using gcc 5.4.1 with newlib 2.4.0 (comparing to gcc 4.8.4 with newlib 2.1.0).

Most problematic code grow up comes from time handling functions (_mktime, gmtime_r_) which pulls malloc and timezones manipulation stuff, etc.

As a partial solution I'm forcing linker to use nano version of functions, but code is still bigger by 8kB.

**Comment by g-oikonomou** [comment] 2018-05-25 18:15
So I just tried a bunch of examples with 2017-q4-major. Surely different resulting code sizes, but I cannot reproduce problems of such magnitude.

Closing this. Happy to re-open if we have details of which example fails to link under what toolchain version.

Note that the recommended / tested toolchain is the one used in the docker image. It is somewhat ancient, but that's a different story...

**Closed by g-oikonomou** 2018-05-25 18:15 UTC
Labels: discussion
