### ISSUE TITLE
New version (4.2) not compiling with TARGET=jn516x

### ISSUE THREAD

**Issue by Apadwee** [contiki-ng/contiki-ng#967] opened 2019-05-20 10:14 UTC

**Comment by g-oikonomou** [comment] 2019-08-31 17:25
Cannot reproduce: I tried `hello-world` inside docker and it built fine for this platform using `release/v4.2` (and `release/v4.3` and `develop`).

Closing for now.

If you are still having issues please provide more information: What example did you try to use, under what environment and using what commands? Then we can re-open.

**Closed by g-oikonomou** 2019-08-31 17:25 UTC
Labels: invalid
