### ISSUE TITLE
Execution problems with old compilers on nrf52840-dongle 

### ISSUE THREAD

**Issue by warner83** [contiki-ng/contiki-ng#1449] opened 2020-11-24 12:25 UTC
Hello, 
I had some issue in executing two examples (specifically, rpl-border-router and example-coap-server) on two nrf52840 dongles compiled on Ubuntu 16.04. The distro ships with an old compiler arm-none-eabi-gcc (15:4.9.3+svn231177-1) 4.9.3.
In particular the code run, however, it seemed to have issues in writing into the NRF_RADIO structure. For instance the channel on the example-coap-server was not properly set. 

Upgrading to a newer compiler,  arm-none-eabi-gcc 5.3.1 20160307 in my case, solved the issue.

**Comment by atiselsts** [comment] 2020-11-24 15:50
We may need to update `Makefile.gcc` to warn the user when such an old version is used.

**Comment by g-oikonomou** [comment] 2020-12-02 20:45
#1462 for the warning.

Leaving this open and moving this to milestone 4.7 for improved handling if we can.

**Comment by alexstanoev** [comment] 2020-12-15 11:50
The root cause was fixed by #1478.

Do we want to revise the warning from #1462?

**Closed** 2021-02-10 20:26 UTC
Labels: bug
